grails-app/taglib/au/org/ala/volunteer/ForumTagLib.groovy
grails-app/views/forum/_taskSummary.gsp
grails-app/views/forum/addForumTopic.gsp
grails-app/views/forum/ajaxProjectForumsList.gsp
grails-app/views/forum/ajaxProjectTaskTopicList.gsp
grails-app/views/forum/editMessage.gsp
grails-app/views/forum/editTopic.gsp
grails-app/views/forum/index.gsp
grails-app/views/forum/markdownHelp.gsp
grails-app/views/forum/postMessage.gsp
grails-app/views/forum/projectForum.gsp
grails-app/views/forum/searchForums.gsp
grails-app/views/forum/viewForumTopic.gsp
web-app/css/digivol-custom.css

@sbearcsiro I'd appreciate if you can have a quick look please.
Cheers,

PR for Feature/volunteer portal 134 -> Convert forum to new design

---

grails-app/conf/ApplicationResources.groovy
grails-app/services/au/org/ala/volunteer/ProjectService.groovy
grails-app/views/index.gsp
grails-app/views/institution/list.gsp
grails-app/views/institutionAdmin/edit.gsp
grails-app/views/project/_projectListThumbnailView.gsp
grails-app/views/project/editBannerImageSettings.gsp
grails-app/views/project/list.gsp
web-app/css/digivol-custom.css
web-app/js/jquery.resizeandcrop.0.4.0/jquery.resizeandcrop.css
web-app/js/jquery.resizeandcrop.0.4.0/jquery.resizeandcrop.js

Please check that it works for you locally

Fixes #143 -> Change image resizing

---

grails-app/controllers/au/org/ala/volunteer/ProjectController.groovy
grails-app/domain/au/org/ala/volunteer/Project.groovy
grails-app/views/project/editBackgroundImageSettings.gsp
grails-app/views/project/index.gsp

Finishes #166 -> Background/Hero image improvements

---

grails-app/controllers/au/org/ala/volunteer/InstitutionAdminController.groovy
grails-app/controllers/au/org/ala/volunteer/UrlMappings.groovy
grails-app/services/au/org/ala/volunteer/UserService.groovy
grails-app/views/institutionAdmin/apply.gsp
grails-app/views/institutionAdmin/edit.gsp

Added logic to search for contact in vp_user and assign them as Institution Admin. If none exists, assigns IA role to Site Admin who approved application. Also fixed permissions to application, enabling it to be accessible and able to be submitted by anonymous user.

#516 Fixed issue with applying for institution without user account

---

grails-app/services/au/org/ala/volunteer/ProjectService.groovy
grails-app/services/au/org/ala/volunteer/TaskLoadService.groovy
grails-app/views/project/editTaskSettings.gsp

Had to move transactional code outside of the actor process and into the service itself.

#552 Fixed issue with deleting tasks from expedition

---

grails-app/controllers/au/org/ala/volunteer/ValidateController.groovy
grails-app/views/validate/noTasks.gsp

Also updated no tasks confirmation page (was out of date).

#554 Fixed issue with validator skipping task.

---

grails-app/controllers/au/org/ala/volunteer/AjaxController.groovy
grails-app/controllers/au/org/ala/volunteer/UrlMappings.groovy
grails-app/services/au/org/ala/volunteer/ExportService.groovy

API exporting DWC fields in JSON for Data Integration Tool.
API accepts a ProjectID as the only parameter.
JSON exported should include:
```
{
"data": [],
"success": true
}
```

DIG-92 Add DwC JSON API for expeditions for the Data Integration Tool

---

build.gradle
grails-app/controllers/au/org/ala/volunteer/ForumController.groovy
grails-app/services/au/org/ala/volunteer/MarkdownService.groovy
grails-app/taglib/au/org/ala/volunteer/ForumTagLib.groovy
grails-app/taglib/au/org/ala/volunteer/MarkdownTagLib.groovy
grails-app/taglib/au/org/ala/volunteer/TranscribeTagLib.groovy
grails-app/taglib/au/org/ala/volunteer/VolunteerTagLib.groovy
src/test/groovy/au/org/ala/volunteer/MarkdownServiceSpec.groovy

Had to create a new service that replaced MarkdownService as well as a replacement taglib.

DIG-74 Replaced abandoned grails-markdown plugin with flexmark.

---

build.gradle
gradle.properties
grails-app/controllers/au/org/ala/volunteer/AjaxController.groovy

Inquire if a user has a validator role for a given project.

DIG-93 Add API for validator role inquiry

---

grails-app/controllers/au/org/ala/volunteer/DigivolActivityInterceptor.groovy
grails-app/init/au/org/ala/volunteer/BootStrap.groovy
grails-app/services/au/org/ala/volunteer/UserService.groovy
grails-app/taglib/au/org/ala/volunteer/TwitterBootstrapTagLib.groovy
grails-app/taglib/au/org/ala/volunteer/VolunteerTagLib.groovy

Replaced usage of `asBoolean()` with `Boolean.parseBoolean()`.

DIG-100 Fixed issue where incorrect usage of asBoolean() was used

---

grails-app/conf/spring/resources.groovy
grails-app/controllers/au/org/ala/volunteer/DigivolActivityInterceptor.groovy
grails-app/controllers/au/org/ala/volunteer/ProjectController.groovy
grails-app/services/au/org/ala/volunteer/UserService.groovy
grails-app/taglib/au/org/ala/volunteer/VolunteerTagLib.groovy
src/main/groovy/au/org/ala/volunteer/BVPServletFilter.groovy

Tested locally and on DigiVol test. Username presents in access log and user activity history.

Update and migrate old Auth Cookie service calls to new Auth Service methods

---

grails-app/views/layouts/_jsUrls.gsp
grails-app/views/project/index.gsp

Replaced truncation library dotdotdot to Cuttr. Displays button to toggle between truncated and full text.

Fixed issue with 'Read More' on expedition description not displaying correctly

---

grails-app/controllers/au/org/ala/volunteer/LeaderBoardController.groovy
grails-app/controllers/au/org/ala/volunteer/ProjectController.groovy
grails-app/services/au/org/ala/volunteer/LeaderBoardService.groovy
grails-app/views/admin/index.gsp
grails-app/views/leaderBoardAdmin/index.gsp

Fixed bugs where ineligible leaderboard users were not being ignored as intended.

DG-120 Fixing issue with ineligible leaderboard users

---

grails-app/services/au/org/ala/volunteer/TaskService.groovy

Fixed SQL exception occurring when stats API was called.
Tested in DigiVol test.
To test, run `/ws/stats`. Output should successfully be returned (in XML format) with no exceptions/errors.

DG-121 Fixed SQL exception occurring in Stats API

---

grails-app/services/au/org/ala/volunteer/ExportService.groovy

When exporting an expedition to a zip file, if one of the fields in the template has the same name as one of the files that is being written and added to the zip file, the export fails with a duplicate file exception.
Added a timestamp to each of the hardcoded filenames so that they are unique at the time of export.

DG-124 Fixed issue with export field names

---

grails-app/services/au/org/ala/volunteer/ProjectService.groovy
grails-app/services/au/org/ala/volunteer/ProjectStagingService.groovy
grails-app/views/project/cloneProjectFragment.gsp

Clone expedition update:
- Added banner/background images
- Added Staging profile (task upload field definitions)
- Updated clone expedition fragment to include above changes

DG-127 Updated clone expedition

---

grails-app/assets/javascripts/digivol-notebook.js
grails-app/controllers/au/org/ala/volunteer/UserController.groovy
grails-app/views/user/show.gsp

* Fixed pin display due to Elastic Search error with searches requesting more than the cap of 10,000 records.
* Fixed issue with ignoring transcriptions with Lat/Long using minutes and seconds (converting them to decimal for Google Maps).
* Updated the pin note display to match project pin display.

DG-82/DG-96 Fixed User notebook map pins display

---

build.gradle
grails-app/services/au/org/ala/volunteer/TaskService.groovy
src/main/groovy/au/org/ala/volunteer/ImageUtils.groovy

Added code to rotate images based on EXIF orientation tag so they display correctly when uploaded.
Used code from Chris G (thanks!)

DG-142 Fixed image distortion issue

---

grails-app/controllers/au/org/ala/volunteer/ImageController.groovy

Older versions of the Wildlife Spotter template have broken JSON where the filename is included but no file extension is listed.
This update checks the disk for the file when the file is requested for display, gets the file extension and creates the corrected taglib code for display.
The newer WS projects don't seem to be broken, so whatever was causing the broken JSON seems to have been fixed (I cannot reproduce it). Had a chat with @sbearcsiro and we agreed that this is enough for now and that if it happens again, we can dig further then.

DG-90 Fixed broken image issue for WS templates

---

grails-app/controllers/au/org/ala/volunteer/FrontPageController.groovy
grails-app/i18n/messages.properties
grails-app/services/au/org/ala/volunteer/FileUploadService.groovy
grails-app/views/frontPage/edit.gsp
src/test/groovy/au/org/ala/volunteer/helper/TaskDataHelper.groovy

Updated frontpage edit UI, added a character counter and maxlength the fields for system message and hero image attribution.
Also added validation to the controller for these as well as hero image filename as none existed.

DG-52 Added max length and character counters to fields

---

grails-app/views/template/_audioTranscribeParams.gsp
grails-app/views/template/_cameratrapTranscribeParams.gsp
grails-app/views/template/_fieldNoteBookTranscribeParams.gsp
grails-app/views/template/_questionnaireTranscribeParams.gsp
grails-app/views/template/edit.gsp

Added a bootstrap accordian to the view. Also fixed up a layout issue with checkboxes for the template config.

DG-128 Updated edit template UI to simplify template usage

---

grails-app/taglib/au/org/ala/volunteer/TranscribeTagLib.groovy
grails-app/views/layouts/digivol-task.gsp
src/main/groovy/au/org/ala/volunteer/SettingDefinition.groovy

Created settings definition for task timeout timer and background save timer.

DG-116 Migrate hardcoded settings to application settings

---

grails-app/controllers/au/org/ala/volunteer/ProjectController.groovy
grails-app/controllers/au/org/ala/volunteer/UserController.groovy
grails-app/services/au/org/ala/volunteer/FieldService.groovy

Updated code from Notebook map update, moved to FieldService and reused this for the project index.
DigiVol Test has been updated. Expedition home page map should display pins of transcriptions (Specimens and Field notes).

DG-75 Expedition Map not displaying pins

---

grails-app/domain/au/org/ala/volunteer/Task.groovy
grails-app/domain/au/org/ala/volunteer/Transcription.groovy
grails-app/domain/au/org/ala/volunteer/User.groovy
grails-app/jobs/au/org/ala/volunteer/TaskFinishedJob.groovy
grails-app/services/au/org/ala/volunteer/FieldSyncService.groovy
grails-app/services/au/org/ala/volunteer/TaskService.groovy
src/test/groovy/au/org/ala/volunteer/FieldSyncServiceSpec.groovy
src/test/groovy/au/org/ala/volunteer/TaskServiceSpec.groovy
src/test/groovy/au/org/ala/volunteer/ValidationServiceSpec.groovy
src/test/groovy/au/org/ala/volunteer/helper/TaskDataHelper.groovy
src/test/resources/logback-test.xml

Fix for DG-150 where transcriptions n and n-1 transcriptions (for a camera trap expedition) occur at the same time create a race condition preventing the task to be marked as fully transcribed.

DG-150 Fix for issue where some transcriptions are not marked as fully transcribed
